# Site settings
title: Delarge Web Design Studio
email: paul@delargedesign.com
description: > # this means to ignore newlines until "baseurl:"
  Your creative web development partner. Bespoke website designs and builds.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://delargedesign.com" # the base hostname & protocol for your site
twitter_username: delarge
github_username:  paulburgess


# Build settings
markdown: kramdown

# We specify the directory for Jekyll so we can use @imports.
sass:
  style:            :compressed
